# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    container_name: travel-api-mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: travel-api
      MYSQL_USER: travel
      MYSQL_PASSWORD: travelapi